fix: Allow legacy PlaceholderField to be deconstructed
This is necessary to allow migrations not to break with
TypeError: "PlaceholderField" missing 1 required positional argument: slotname