Update example "Handling relations" to uses a "ManyToManyField"
In the doc example of "Handling relations", we have to make some changes because that back these errors:
AttributeError: module 'django.db.models' has no attribute 'ManyToMany'
project.MyPageExtension.page_categories: (fields.W340) null has no effect on ManyToManyField.