Update sitemap.rst - Django 1.10 no longer specify views as a string
Without these changes this error appears :
raise TypeError('view must be a callable or a list/tuple in the case of include().')
TypeError: view must be a callable or a list/tuple in the case of include().