revert: changes in the cms user permission
Reverting the patch from this PR, since it is causing crash in some
websites with this error:

```python
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_museumday`.`cms_pageuser`, CONSTRAINT `cms_pageuser_created_by_id_8e9fbf83_fk_users_user_id` FOREIGN KEY (`created_by_id`) REFERENCES `users_user` (`id`))')
```

- https://django-cmsworkspace.slack.com/archives/C01J7H87KFC/p1621333264008900

Authored-by: Vinit Kumar <vinit.kumar@socialschools.nl>
Signed-off-by: Vinit Kumar <vinit.kumar@socialschools.nl>