Django 3.2 : Add , 'cms_page_edit_plugin' to is_cms_request to avoid
TODO: we need to add test for this. This bug slipped without tests and
only when a setting flag was set to True which is False by default.

This takes care of this crash:
```
File "...../cms/toolbar/utils.py", line 66, in get_plugin_tree_as_json
    copy_to_clipboard = placeholder.pk == toolbar.clipboard.pk
AttributeError: 'EmptyToolbar' object has no attribute 'clipboard'
```