fix: Allow legacy PlaceholderField to be deconstructed (#8248)
* fix: Allow legacy PlaceholderField to be deconstructed

This is necessary to allow migrations not to break with
TypeError: "PlaceholderField" missing 1 required positional argument: slotname

* fix: add `system_check_removed_details` message to `PlaceholderField`

* Update fuzzy_int.py

---------

Co-authored-by: Fabian Braun <fsbraun@gmx.de>